apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerphone
  labels:
    app: customerphone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerphone
  template:
    metadata:
      labels:
        app: customerphone
    spec:
      containers:
        - name: customerphone
          image: "username/customerphone:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
