---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lost
  labels:
    app: lost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lost
  template:
    metadata:
      labels:
        app: lost
    spec:
      containers:
        - name: lost
          image: username/lost:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rent
  labels:
    app: rent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rent
  template:
    metadata:
      labels:
        app: rent
    spec:
      containers:
        - name: rent
          image: username/rent:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerphone
  labels:
    app: customerphone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerphone
  template:
    metadata:
      labels:
        app: customerphone
    spec:
      containers:
        - name: customerphone
          image: username/customerphone:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: username/customer:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentphone
  labels:
    app: rentphone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rentphone
  template:
    metadata:
      labels:
        app: rentphone
    spec:
      containers:
        - name: rentphone
          image: username/rentphone:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: lost
  labels:
    app: lost
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: lost


---


apiVersion: v1
kind: Service
metadata:
  name: rent
  labels:
    app: rent
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: rent


---


apiVersion: v1
kind: Service
metadata:
  name: customerphone
  labels:
    app: customerphone
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customerphone


---


apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    app: customer
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customer


---


apiVersion: v1
kind: Service
metadata:
  name: rentphone
  labels:
    app: rentphone
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: rentphone

